[tool.poetry]
name = "streamlit-agent"
version = "0.1.0"
description = ""
authors = ["Tim Conkling <tconkling@gmail.com>", "Joshua Carroll <joshua.carroll@snowflake.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "streamlit_agent"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
langchain = "^0.3.25"        
openai = ">=1.6.1"
duckduckgo-search = ">4.0"
pypdf = "^3.12.2"
sentence-transformers = "^2.2.2"
tabulate = "^0.9.0"
streamlit = "^1.35.0"
streamlit-folium = "^0.23.2"
folium = "^0.17.0"
docarray = "^0.38.0"
langchain-experimental = "0.3.4"  
langchain-community = "^0.3.19"        # or latest
langchain-openai = "^0.3.19"            # or latest
langchainhub = "^0.1.21"               # or latest
langchain-tavily = "^0.1.0"   
langchain-groq = "^0.3.7"
langchain-mcp-adapters = "^0.1.9"
tavily-python = "^0.3.0"      # Direct Tavily API client (latest stable)
numexpr = "^2.8.8"
langchain-google-genai = "^2.1.0"
matplotlib = "^3.9.0"
psycopg2-binary = "~=2.9"
fastmcp=">=0.2.0"
cryptography = "<42"
faiss-cpu = "^1.8.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4.1"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
